name: kobi
description: "calendar/alarm/mail"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+3

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^16.2.0      #알림
  flutter_timezone: ^1.0.8           #현재 기기의 시간대 반환하기
  timezone: ^0.9.2                  #timezone (korea/seoul or korea standard time)
  device_info_plus: ^9.1.1
  http: ^1.1.2
  path_provider: ^2.1.1
  image: ^4.1.3
  get: ^4.6.6                      #Get Controller
  flutter_screenutil: ^5.9.0       # 화면 비율
  google_fonts: ^6.1.0             #폰트
  syncfusion_flutter_calendar: ^24.1.41 #캘린더
  audio_session: ^0.1.18
  flutter_sound: ^9.2.13
  permission_handler: ^11.1.0
#  flutter_snowboy: ^0.1.2+1       #시리
  audiofileplayer: ^2.1.1
  flutter_native_splash: ^2.3.8    #splash 라이브러리
  firebase_core: ^2.24.2          #firebase
  firebase_messaging: ^14.7.9     #firebase 푸시알림
  flutter_secure_storage: ^9.0.0   #저장 공간
  google_sign_in: ^6.2.1           #구글 로그인(앞단)
  flutter_tts: ^3.8.5
  animated_text_kit: ^4.2.2         #텍스트 애니메이션
  loading_animation_widget: ^1.2.0+4  #로딩 애니메이션
  audioplayers: ^5.2.1
  dotted_border: ^2.1.0
  collection: ^1.18.0
  siri_wave: ^2.0.0+1               #시리같은 스피커
  intl: ^0.18.1
  wrapped_korean_text: ^0.0.3      #한글 띄어쓰기 라이브러리
  flutter_localization: ^0.2.0    #우리나라로 로컬화
  scroll_date_picker: ^3.7.3      #달력 년/월/일 스크롤로 선택
  url_launcher: ^6.2.2            #url로 보내주는 라이브러리
  flutter_datetime_picker_plus: ^2.1.0
  syncfusion_flutter_datepicker: ^24.1.43
  flutter_launcher_icons: ^0.13.1
  infinite_scroll_pagination: ^4.0.0
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/


  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Thin.otf
          weight: 100
        - asset: assets/fonts/NotoSansKR-Light.otf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/fonts/NotoSansKR-Black.otf
          weight: 900
    - family: Jua
      fonts:
        - asset: assets/fonts/Jua-Regular.ttf