// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWCGJD4ueKGfno-vHh3dTEMSL42F8w10M',
    appId: '1:372113464838:android:e06615b1b6954efec8ad87',
    messagingSenderId: '372113464838',
    projectId: 'compact-lacing-408503',
    storageBucket: 'compact-lacing-408503.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAATqX3_zJBzsu0a2q9_nCzCrGs4R3xYqQ',
    appId: '1:372113464838:ios:420f170a8cebed28c8ad87',
    messagingSenderId: '372113464838',
    projectId: 'compact-lacing-408503',
    storageBucket: 'compact-lacing-408503.appspot.com',
    androidClientId: '372113464838-6spk4rl61l9ahjn1a7pjdo0n7mgs3q5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.kobi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAATqX3_zJBzsu0a2q9_nCzCrGs4R3xYqQ',
    appId: '1:372113464838:ios:319eaa2955eb7bf7c8ad87',
    messagingSenderId: '372113464838',
    projectId: 'compact-lacing-408503',
    storageBucket: 'compact-lacing-408503.appspot.com',
    androidClientId: '372113464838-6spk4rl61l9ahjn1a7pjdo0n7mgs3q5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.kobi.RunnerTests',
  );
}
